from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, time
from typing import Any


@dataclass
class Task:
    """Represents a single pet care activity."""

    task_id: str
    title: str
    category: str
    duration_minutes: int
    priority: int
    frequency: str
    preferred_time_window: str
    last_completed_on: date | None = None
    completed_today: bool = False

    def is_due(self, on_date: date) -> bool:
        """Return whether this task should be scheduled on a given date."""
        raise NotImplementedError

    def mark_completed(self, on_date: date) -> None:
        """Mark this task as completed on a specific date."""
        raise NotImplementedError

    def mark_incomplete(self) -> None:
        """Reset completion status for this task."""
        raise NotImplementedError

    def get_effective_priority(self, pet: Pet) -> int:
        """Compute adjusted priority using pet context and special needs."""
        raise NotImplementedError


@dataclass
class Pet:
    """Stores profile and care-context information for a pet."""

    pet_id: str
    name: str
    species: str
    breed: str
    age_years: int
    special_needs: list[str] = field(default_factory=list)

    def update_profile(self, updates: dict[str, Any]) -> None:
        """Update pet profile fields using a partial update map."""
        raise NotImplementedError

    def add_special_need(self, need: str) -> None:
        """Add a special need to this pet's profile."""
        raise NotImplementedError

    def remove_special_need(self, need: str) -> bool:
        """Remove a special need if present and return success."""
        raise NotImplementedError

    def get_care_context(self) -> str:
        """Return a concise summary of care-related context."""
        raise NotImplementedError


@dataclass
class ScheduledTask:
    """A task assigned to a concrete time slot in a schedule."""

    task: Task
    start_time: time
    end_time: time
    reason: str

    def duration_minutes(self) -> int:
        """Return scheduled duration in minutes."""
        raise NotImplementedError

    def overlaps(self, other: ScheduledTask) -> bool:
        """Return True when two scheduled tasks overlap in time."""
        raise NotImplementedError


@dataclass
class Schedule:
    """Represents the final daily plan generated by the planner."""

    schedule_date: date
    total_minutes_available: int
    total_minutes_used: int = 0
    items: list[ScheduledTask] = field(default_factory=list)
    explanations: list[str] = field(default_factory=list)

    def add_item(self, item: ScheduledTask) -> bool:
        """Attempt to add a scheduled item and return whether it fit."""
        raise NotImplementedError

    def remaining_minutes(self) -> int:
        """Return how many minutes are still unallocated."""
        raise NotImplementedError

    def is_full(self) -> bool:
        """Return True when no more task time can be allocated."""
        raise NotImplementedError

    def to_display_rows(self) -> list[dict[str, Any]]:
        """Return a UI-friendly representation of schedule rows."""
        raise NotImplementedError


@dataclass
class Owner:
    """Represents the app user and their scheduling constraints."""

    owner_id: str
    name: str
    available_minutes_per_day: int
    preferences: dict[str, Any] = field(default_factory=dict)
    tasks: list[Task] = field(default_factory=list)
    pet: Pet | None = None

    def add_task(self, task: Task) -> None:
        """Add a new care task to the owner's task list."""
        raise NotImplementedError

    def remove_task(self, task_id: str) -> bool:
        """Remove a task by id and return success."""
        raise NotImplementedError

    def update_task(self, task_id: str, updates: dict[str, Any]) -> bool:
        """Update a task by id using partial field updates."""
        raise NotImplementedError

    def get_tasks(self) -> list[Task]:
        """Return all tasks associated with the owner."""
        raise NotImplementedError

    def get_due_tasks(self, on_date: date) -> list[Task]:
        """Return only tasks due for the specified date."""
        raise NotImplementedError


class Planner:
    """Core scheduling engine that builds a daily plan."""

    def __init__(self, strategy: str = "priority-first") -> None:
        self.strategy = strategy

    def generate_daily_schedule(self, owner: Owner, pet: Pet, on_date: date) -> Schedule:
        """Build and return the final daily schedule."""
        raise NotImplementedError

    def filter_due_tasks(self, tasks: list[Task], on_date: date) -> list[Task]:
        """Filter tasks down to only those due on the target date."""
        raise NotImplementedError

    def prioritize_tasks(self, tasks: list[Task], pet: Pet) -> list[Task]:
        """Order tasks by effective priority and scheduling policy."""
        raise NotImplementedError

    def allocate_within_time(self, tasks: list[Task], available_minutes: int) -> list[Task]:
        """Select tasks that fit within available daily time."""
        raise NotImplementedError

    def resolve_conflicts(self, tasks: list[Task]) -> list[Task]:
        """Resolve collisions, dependencies, or ordering conflicts."""
        raise NotImplementedError

    def build_explanations(self, selected: list[Task], skipped: list[Task]) -> list[str]:
        """Produce human-readable reasons for selection decisions."""
        raise NotImplementedError
