from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, time, datetime, timedelta
from enum import Enum
from typing import Any


class Frequency(Enum):
    """Supported task frequency patterns."""
    DAILY = "daily"
    EVERY_OTHER_DAY = "every_other_day"
    WEEKLY = "weekly"
    TWICE_WEEKLY = "twice_weekly"
    AS_NEEDED = "as_needed"


@dataclass
class Task:
    """Represents a single pet care activity."""

    task_id: str
    title: str
    category: str
    duration_minutes: int
    priority: int
    frequency: Frequency
    preferred_time_window: str
    completion_history: list[date] = field(default_factory=list)

    @property
    def last_completed_on(self) -> date | None:
        """Return the most recent completion date, or None if never completed."""
        return self.completion_history[-1] if self.completion_history else None

    @property
    def completed_today(self) -> bool:
        """Return whether this task was completed on today's date."""
        today = date.today()
        return today in self.completion_history

    def is_due(self, on_date: date) -> bool:
        """Check if task is due on the specified date based on frequency."""
        raise NotImplementedError

    def mark_completed(self, on_date: date) -> None:
        """Record task completion on the given date."""
        if on_date not in self.completion_history:
            self.completion_history.append(on_date)

    def mark_incomplete(self) -> None:
        """Clear all completion history for this task."""
        self.completion_history.clear()

    def get_effective_priority(self, pet: Pet, on_date: date) -> int:
        """Calculate priority adjusted for pet context and time-based factors."""
        raise NotImplementedError


@dataclass
class Pet:
    """Stores profile and care-context information for a pet."""

    pet_id: str
    name: str
    species: str
    breed: str
    age_years: int
    special_needs: list[str] = field(default_factory=list)

    def update_profile(self, updates: dict[str, Any]) -> None:
        """Update pet profile fields from a dictionary of changes."""
        for key, value in updates.items():
            if hasattr(self, key):
                setattr(self, key, value)
            else:
                raise ValueError(f"Pet has no attribute '{key}'.")

    def add_special_need(self, need: str) -> None:
        """Add a special care need for this pet."""
        if need not in self.special_needs:
            self.special_needs.append(need)

    def remove_special_need(self, need: str) -> bool:
        """Remove a special care need and return success."""
        if need in self.special_needs:
            self.special_needs.remove(need)
            return True
        return False

    def get_care_context(self) -> str:
        """Generate a summary of the pet's profile and care needs."""
        context = f"{self.name} is a {self.age_years}-year-old {self.species} ({self.breed})"
        if self.special_needs:
            context += f". Special needs: {', '.join(self.special_needs)}"
        return context


@dataclass
class ScheduledTask:
    """A task assigned to a concrete time slot in a schedule."""

    task: Task
    start_time: time
    end_time: time
    reason: str

    def duration_minutes(self) -> int:
        """Calculate task duration in minutes based on start and end times."""
        raise NotImplementedError

    def overlaps(self, other: ScheduledTask) -> bool:
        """Check if this task conflicts with another scheduled task."""
        raise NotImplementedError


@dataclass
class Schedule:
    """Represents the final daily plan generated by the planner."""

    schedule_date: date
    total_minutes_available: int
    total_minutes_used: int = 0
    items: list[ScheduledTask] = field(default_factory=list)
    explanations: list[str] = field(default_factory=list)
    skipped_tasks_with_reasons: dict[str, str] = field(default_factory=dict)

    def add_item(self, item: ScheduledTask) -> bool:
        """Add a scheduled task to the plan if there's available time."""
        raise NotImplementedError

    def remaining_minutes(self) -> int:
        """Calculate unallocated time remaining in the schedule."""
        raise NotImplementedError

    def is_full(self) -> bool:
        """Check if the schedule has reached capacity."""
        raise NotImplementedError

    def to_display_rows(self) -> list[dict[str, Any]]:
        """Format schedule for UI display as a list of row dictionaries."""
        raise NotImplementedError


@dataclass
class Owner:
    """Represents the app user and their scheduling constraints."""

    owner_id: str
    name: str
    available_minutes_per_day: int
    preferences: dict[str, Any] = field(default_factory=dict)
    tasks: list[Task] = field(default_factory=list)
    pet: Pet | None = None

    def add_task(self, task: Task) -> None:
        """Add a new task to the owner's task list (rejects duplicate IDs)."""
        if any(t.task_id == task.task_id for t in self.tasks):
            raise ValueError(f"Task with id '{task.task_id}' already exists.")
        self.tasks.append(task)

    def remove_task(self, task_id: str) -> bool:
        """Remove a task by ID (raises ValueError if not found)."""
        original_length = len(self.tasks)
        self.tasks = [t for t in self.tasks if t.task_id != task_id]
        if len(self.tasks) == original_length:
            raise ValueError(f"Task with id '{task_id}' not found.")
        return True

    def update_task(self, task_id: str, updates: dict[str, Any]) -> bool:
        """Update task fields by ID (raises ValueError if not found or invalid field)."""
        for task in self.tasks:
            if task.task_id == task_id:
                for key, value in updates.items():
                    if hasattr(task, key):
                        setattr(task, key, value)
                    else:
                        raise ValueError(f"Task has no attribute '{key}'.")
                return True
        raise ValueError(f"Task with id '{task_id}' not found.")

    def get_tasks(self) -> list[Task]:
        """Return all tasks in the owner's task list."""
        return self.tasks

    def get_due_tasks(self, on_date: date) -> list[Task]:
        """Return tasks that are due on the specified date."""
        raise NotImplementedError


class Planner:
    """Core scheduling engine that builds a daily plan."""

    def __init__(self, strategy: str = "priority-first") -> None:
        """Initialize planner with scheduling strategy."""
        self.strategy = strategy

    def generate_daily_schedule(self, owner: Owner, pet: Pet, on_date: date) -> Schedule:
        """Generate an optimized daily schedule based on tasks and constraints."""
        raise NotImplementedError

    def filter_due_tasks(self, tasks: list[Task], on_date: date) -> list[Task]:
        """Filter tasks to only those due on the specified date."""
        raise NotImplementedError

    def prioritize_tasks(self, tasks: list[Task], pet: Pet, on_date: date) -> list[Task]:
        """Sort tasks by effective priority considering pet context and recency."""
        raise NotImplementedError

    def allocate_within_time(self, tasks: list[Task], available_minutes: int) -> dict[str, Any]:
        """Select tasks that fit within time constraints and return selected/skipped info."""
        raise NotImplementedError

    def resolve_conflicts(self, tasks: list[Task]) -> list[Task]:
        """Resolve scheduling conflicts and enforce task dependencies."""
        raise NotImplementedError

    def build_explanations(self, selected: list[Task], skipped_info: dict[str, str]) -> list[str]:
        """Generate human-readable explanations for scheduling decisions."""
        raise NotImplementedError
