from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, time, datetime, timedelta
from enum import Enum
from typing import Any


class Frequency(Enum):
    """Supported task frequency patterns."""
    DAILY = "daily"
    EVERY_OTHER_DAY = "every_other_day"
    WEEKLY = "weekly"
    TWICE_WEEKLY = "twice_weekly"
    AS_NEEDED = "as_needed"


@dataclass
class Task:
    """Represents a single pet care activity."""

    task_id: str
    title: str
    category: str
    duration_minutes: int
    priority: int
    frequency: Frequency
    preferred_time_window: str
    completion_history: list[date] = field(default_factory=list)

    @property
    def last_completed_on(self) -> date | None:
        """Return the most recent completion date, or None if never completed."""
        return self.completion_history[-1] if self.completion_history else None

    @property
    def completed_today(self) -> bool:
        """Return whether this task was completed on today's date."""
        today = date.today()
        return today in self.completion_history

    def is_due(self, on_date: date) -> bool:
        """Return whether this task should be scheduled on a given date."""
        raise NotImplementedError

    def mark_completed(self, on_date: date) -> None:
        """Mark this task as completed on a specific date."""
        raise NotImplementedError

    def mark_incomplete(self) -> None:
        """Reset completion status for this task."""
        raise NotImplementedError

    def get_effective_priority(self, pet: Pet, on_date: date) -> int:
        """Compute adjusted priority using pet context, special needs, and recency."""
        raise NotImplementedError


@dataclass
class Pet:
    """Stores profile and care-context information for a pet."""

    pet_id: str
    name: str
    species: str
    breed: str
    age_years: int
    special_needs: list[str] = field(default_factory=list)

    def update_profile(self, updates: dict[str, Any]) -> None:
        """Update pet profile fields using a partial update map."""
        raise NotImplementedError

    def add_special_need(self, need: str) -> None:
        """Add a special need to this pet's profile."""
        raise NotImplementedError

    def remove_special_need(self, need: str) -> bool:
        """Remove a special need if present and return success."""
        raise NotImplementedError

    def get_care_context(self) -> str:
        """Return a concise summary of care-related context."""
        raise NotImplementedError


@dataclass
class ScheduledTask:
    """A task assigned to a concrete time slot in a schedule."""

    task: Task
    start_time: time
    end_time: time
    reason: str

    def duration_minutes(self) -> int:
        """Return scheduled duration in minutes."""
        raise NotImplementedError

    def overlaps(self, other: ScheduledTask) -> bool:
        """Return True when two scheduled tasks overlap in time."""
        raise NotImplementedError


@dataclass
class Schedule:
    """Represents the final daily plan generated by the planner."""

    schedule_date: date
    total_minutes_available: int
    total_minutes_used: int = 0
    items: list[ScheduledTask] = field(default_factory=list)
    explanations: list[str] = field(default_factory=list)
    skipped_tasks_with_reasons: dict[str, str] = field(default_factory=dict)

    def add_item(self, item: ScheduledTask) -> bool:
        """Attempt to add a scheduled item and return whether it fit."""
        raise NotImplementedError

    def remaining_minutes(self) -> int:
        """Return how many minutes are still unallocated."""
        raise NotImplementedError

    def is_full(self) -> bool:
        """Return True when no more task time can be allocated."""
        raise NotImplementedError

    def to_display_rows(self) -> list[dict[str, Any]]:
        """Return a UI-friendly representation of schedule rows."""
        raise NotImplementedError


@dataclass
class Owner:
    """Represents the app user and their scheduling constraints."""

    owner_id: str
    name: str
    available_minutes_per_day: int
    preferences: dict[str, Any] = field(default_factory=dict)
    tasks: list[Task] = field(default_factory=list)
    pet: Pet | None = None

    def add_task(self, task: Task) -> None:
        """Add a new care task to the owner's task list."""
        if any(t.task_id == task.task_id for t in self.tasks):
            raise ValueError(f"Task with id '{task.task_id}' already exists.")
        self.tasks.append(task)

    def remove_task(self, task_id: str) -> bool:
        """Remove a task by id and return success. Raises ValueError if not found."""
        original_length = len(self.tasks)
        self.tasks = [t for t in self.tasks if t.task_id != task_id]
        if len(self.tasks) == original_length:
            raise ValueError(f"Task with id '{task_id}' not found.")
        return True

    def update_task(self, task_id: str, updates: dict[str, Any]) -> bool:
        """Update a task by id using partial field updates. Raises ValueError if not found."""
        for task in self.tasks:
            if task.task_id == task_id:
                for key, value in updates.items():
                    if hasattr(task, key):
                        setattr(task, key, value)
                    else:
                        raise ValueError(f"Task has no attribute '{key}'.")
                return True
        raise ValueError(f"Task with id '{task_id}' not found.")

    def get_tasks(self) -> list[Task]:
        """Return all tasks associated with the owner."""
        raise NotImplementedError

    def get_due_tasks(self, on_date: date) -> list[Task]:
        """Return only tasks due for the specified date."""
        raise NotImplementedError


class Planner:
    """Core scheduling engine that builds a daily plan."""

    def __init__(self, strategy: str = "priority-first") -> None:
        self.strategy = strategy

    def generate_daily_schedule(self, owner: Owner, pet: Pet, on_date: date) -> Schedule:
        """Build and return the final daily schedule."""
        raise NotImplementedError

    def filter_due_tasks(self, tasks: list[Task], on_date: date) -> list[Task]:
        """Filter tasks down to only those due on the target date."""
        raise NotImplementedError

    def prioritize_tasks(self, tasks: list[Task], pet: Pet, on_date: date) -> list[Task]:
        """Order tasks by effective priority and scheduling policy."""
        raise NotImplementedError

    def allocate_within_time(self, tasks: list[Task], available_minutes: int) -> dict[str, Any]:
        """Select tasks that fit within available daily time.
        
        Returns:
            dict with keys 'selected' (list[Task]), 'skipped' (list[Task]), 
            'skipped_reasons' (dict[str, str]).
        """
        raise NotImplementedError

    def resolve_conflicts(self, tasks: list[Task]) -> list[Task]:
        """Resolve collisions, dependencies, or ordering conflicts."""
        raise NotImplementedError

    def build_explanations(self, selected: list[Task], skipped_info: dict[str, str]) -> list[str]:
        """Produce human-readable reasons for selection decisions.
        
        Args:
            selected: list of tasks that made it into the schedule
            skipped_info: dict mapping task_id to skip reason
            
        Returns:
            list of explanation strings for display
        """
        raise NotImplementedError
